Repository mantoniu/Divertech, pull requests merged in 2024-05, with the labels that each got.

#39 Feature/add admin behavior
  divertech/app/src/main/AndroidManifest.xml
  divertech/app/src/main/java/Si3/divertech/AdminReportActivity.java
  divertech/app/src/main/java/Si3/divertech/CreateEventActivity.java
  divertech/app/src/main/java/Si3/divertech/EventActivity.java
  divertech/app/src/main/java/Si3/divertech/FeedFragment.java
  divertech/app/src/main/java/Si3/divertech/ListEventActivity.java
  divertech/app/src/main/java/Si3/divertech/LoginActivity.java
  divertech/app/src/main/java/Si3/divertech/MainActivity.java
  divertech/app/src/main/java/Si3/divertech/MultiPagesActivity.java
  divertech/app/src/main/java/Si3/divertech/User.java
  divertech/app/src/main/java/Si3/divertech/UserData.java
  divertech/app/src/main/res/drawable/bell.xml
  divertech/app/src/main/res/drawable/cancel.xml
  divertech/app/src/main/res/drawable/check.xml
  divertech/app/src/main/res/drawable/edit.xml
  divertech/app/src/main/res/drawable/feed_admin.xml
  divertech/app/src/main/res/layout/activity_admin_event.xml
  divertech/app/src/main/res/layout/activity_admin_new_event.xml
  divertech/app/src/main/res/layout/activity_admin_report.xml
  divertech/app/src/main/res/layout/activity_multi_pages_admin.xml
  divertech/app/src/main/res/values/strings.xml
Labels: enhancement

#46 Ajout du profil de la personne qui écrit la notif pour l'organisateur
  divertech/app/src/main/java/Si3/divertech/CreateEventActivity.java
  divertech/app/src/main/java/Si3/divertech/EventActivity.java
  divertech/app/src/main/java/Si3/divertech/FeedFragment.java
  divertech/app/src/main/java/Si3/divertech/MultiPagesAdminActivity.java
  divertech/app/src/main/java/Si3/divertech/Notification.java
  divertech/app/src/main/java/Si3/divertech/NotificationAdapter.java
  divertech/app/src/main/java/Si3/divertech/NotificationCreator.java
  divertech/app/src/main/java/Si3/divertech/NotificationList.java
  divertech/app/src/main/java/Si3/divertech/UserData.java
  divertech/app/src/main/res/layout/activity_multi_pages_admin.xml
Labels: enhancement

#54 Ajout de détails visuels
  divertech/app/src/main/java/Si3/divertech/ClickableActivity.java
  divertech/app/src/main/java/Si3/divertech/EventActivity.java
  divertech/app/src/main/java/Si3/divertech/FeedFragment.java
  divertech/app/src/main/java/Si3/divertech/ListEvent.java
  divertech/app/src/main/java/Si3/divertech/ListEventActivity.java
  divertech/app/src/main/java/Si3/divertech/MainActivity.java
  divertech/app/src/main/java/Si3/divertech/MapActivity.java
  divertech/app/src/main/java/Si3/divertech/NotificationList.java
  divertech/app/src/main/res/drawable/calendar.png
  divertech/app/src/main/res/drawable/calendar.xml
  divertech/app/src/main/res/drawable/gps.png
  divertech/app/src/main/res/drawable/location.xml
  divertech/app/src/main/res/drawable/message.png
  divertech/app/src/main/res/drawable/parking.png
  divertech/app/src/main/res/layout/activity_admin_event.xml
  divertech/app/src/main/res/layout/activity_admin_new_event.xml
  divertech/app/src/main/res/layout/activity_event.xml
  divertech/app/src/main/res/layout/activity_parking.xml
  divertech/app/src/main/res/layout/fragment_feed.xml
  divertech/app/src/main/res/layout/notification_item.xml
  divertech/app/src/main/res/values/strings.xml
  divertech/app/src/main/res/values/themes.xml
Labels: enhancement

#58 Gps2
  divertech/app/src/main/java/Si3/divertech/EventActivity.java
  divertech/app/src/main/java/Si3/divertech/FeedFragment.java
  divertech/app/src/main/java/Si3/divertech/MapActivity.java
  divertech/app/src/main/java/Si3/divertech/map/EventPopupMarker.java
  divertech/app/src/main/java/Si3/divertech/map/PopupMarker.java
  divertech/app/src/main/java/Si3/divertech/map/PopupMarkerFactory.java
  divertech/app/src/main/java/Si3/divertech/map/SelfPopupMarker.java
  divertech/app/src/main/res/drawable/self_position.xml
  divertech/app/src/main/res/layout/marker_popup_layout.xml
  divertech/app/src/main/res/layout/marker_popup_layout_self.xml
Labels: enhancement

#57 Refactor FeedFragment et fix de bugs
  divertech/app/src/main/AndroidManifest.xml
  divertech/app/src/main/java/Si3/divertech/ClickableActivity.java
  divertech/app/src/main/java/Si3/divertech/CreateEventActivity.java
  divertech/app/src/main/java/Si3/divertech/EventActivity.java
  divertech/app/src/main/java/Si3/divertech/FeedFragment.java
  divertech/app/src/main/java/Si3/divertech/FootMenu.java
  divertech/app/src/main/java/Si3/divertech/HeaderMenu.java
  divertech/app/src/main/java/Si3/divertech/ListEvent.java
  divertech/app/src/main/java/Si3/divertech/ListEventActivity.java
  divertech/app/src/main/java/Si3/divertech/LoginActivity.java
  divertech/app/src/main/java/Si3/divertech/MainActivity.java
  divertech/app/src/main/java/Si3/divertech/MapActivity.java
  divertech/app/src/main/java/Si3/divertech/MultiPagesActivity.java
  divertech/app/src/main/java/Si3/divertech/MultiPagesAdminActivity.java
  divertech/app/src/main/java/Si3/divertech/ProfileActivity.java
  divertech/app/src/main/java/Si3/divertech/RegisterActivity.java
  divertech/app/src/main/java/Si3/divertech/events/AdminEventActivity.java
  divertech/app/src/main/java/Si3/divertech/events/Event.java
  divertech/app/src/main/java/Si3/divertech/events/EventActivities.java
  divertech/app/src/main/java/Si3/divertech/events/EventActivitiesFactory.java
  divertech/app/src/main/java/Si3/divertech/events/EventActivity.java
  divertech/app/src/main/java/Si3/divertech/events/EventAdapter.java
  divertech/app/src/main/java/Si3/divertech/events/EventList.java
  divertech/app/src/main/java/Si3/divertech/feed/AdminNotificationFeed.java
  divertech/app/src/main/java/Si3/divertech/feed/EventFeed.java
  divertech/app/src/main/java/Si3/divertech/feed/Feed.java
  divertech/app/src/main/java/Si3/divertech/feed/FeedFactory.java
  divertech/app/src/main/java/Si3/divertech/feed/FeedType.java
  divertech/app/src/main/java/Si3/divertech/feed/NotificationFeed.java
  divertech/app/src/main/java/Si3/divertech/map/EventPopupMarker.java
  divertech/app/src/main/java/Si3/divertech/notifications/Notification.java
  divertech/app/src/main/java/Si3/divertech/notifications/NotificationAdapter.java
  divertech/app/src/main/java/Si3/divertech/notifications/NotificationCreator.java
  divertech/app/src/main/java/Si3/divertech/notifications/NotificationList.java
  divertech/app/src/main/java/Si3/divertech/notifications/NotificationTypeAdapter.java
  divertech/app/src/main/java/Si3/divertech/notifications/NotificationTypes.java
  divertech/app/src/main/java/Si3/divertech/qr_reader/CameraPreviewActivity.java
  divertech/app/src/main/java/Si3/divertech/users/User.java
  divertech/app/src/main/java/Si3/divertech/users/UserData.java
  divertech/app/src/main/java/Si3/divertech/users/UserType.java
  divertech/app/src/main/res/layout/activity_admin_event.xml
  divertech/app/src/main/res/layout/activity_admin_new_event.xml
  divertech/app/src/main/res/layout/activity_admin_report.xml
  divertech/app/src/main/res/layout/activity_event.xml
  divertech/app/src/main/res/layout/activity_multi_pages.xml
  divertech/app/src/main/res/layout/activity_multi_pages_admin.xml
Labels: bug, enhancement

#59 Ajout cropper image et création/édition d'event
  divertech/app/build.gradle.kts
  divertech/app/src/main/AndroidManifest.xml
  divertech/app/src/main/java/Si3/divertech/CreateEventActivity.java
  divertech/app/src/main/java/Si3/divertech/ImageCropperActivity.java
  divertech/app/src/main/java/Si3/divertech/ListEventActivity.java
  divertech/app/src/main/java/Si3/divertech/LoginActivity.java
  divertech/app/src/main/java/Si3/divertech/MapActivity.java
  divertech/app/src/main/java/Si3/divertech/ParkingActivity.java
  divertech/app/src/main/java/Si3/divertech/ProfileActivity.java
  divertech/app/src/main/java/Si3/divertech/events/AdminEventActivity.java
  divertech/app/src/main/java/Si3/divertech/events/Event.java
  divertech/app/src/main/java/Si3/divertech/events/EventActivities.java
  divertech/app/src/main/java/Si3/divertech/events/EventList.java
  divertech/app/src/main/java/Si3/divertech/notifications/NotificationCreator.java
  divertech/app/src/main/java/Si3/divertech/qr_reader/CameraPreviewActivity.java
  divertech/app/src/main/java/Si3/divertech/users/User.java
  divertech/app/src/main/java/Si3/divertech/users/UserData.java
  divertech/app/src/main/java/Si3/divertech/utils/DateListener.java
  divertech/app/src/main/java/Si3/divertech/utils/DatePickerFragment.java
  divertech/app/src/main/java/Si3/divertech/utils/DateUtils.java
  divertech/app/src/main/java/Si3/divertech/utils/UploadUtils.java
  divertech/app/src/main/res/drawable/edit_picture.xml
  divertech/app/src/main/res/drawable/share.xml
  divertech/app/src/main/res/layout/activity_admin_event.xml
  divertech/app/src/main/res/layout/activity_admin_new_event.xml
  divertech/app/src/main/res/layout/activity_profile.xml
  divertech/app/src/main/res/layout/share_popup.xml
  divertech/app/src/main/res/values/strings.xml
  divertech/settings.gradle.kts
Labels: enhancement

#61 Patch bug des autorisations
  divertech/app/src/main/AndroidManifest.xml
  divertech/app/src/main/java/Si3/divertech/ImageCropperActivity.java
  divertech/app/src/main/java/Si3/divertech/events/EventActivity.java
Labels: bug

#65 Utilisation du pattern MVC pour la gestion du profil
  divertech/app/src/main/AndroidManifest.xml
  divertech/app/src/main/java/Si3/divertech/CreateEventActivity.java
  divertech/app/src/main/java/Si3/divertech/HeaderMenu.java
  divertech/app/src/main/java/Si3/divertech/LaunchActivity.java
  divertech/app/src/main/java/Si3/divertech/ListEventActivity.java
  divertech/app/src/main/java/Si3/divertech/LoginActivity.java
  divertech/app/src/main/java/Si3/divertech/MainActivity.java
  divertech/app/src/main/java/Si3/divertech/MapActivity.java
  divertech/app/src/main/java/Si3/divertech/MultiPagesActivity.java
  divertech/app/src/main/java/Si3/divertech/MultiPagesAdminActivity.java
  divertech/app/src/main/java/Si3/divertech/ParkingActivity.java
  divertech/app/src/main/java/Si3/divertech/ProfileActivity.java
  divertech/app/src/main/java/Si3/divertech/RequireUserActivity.java
  divertech/app/src/main/java/Si3/divertech/events/AdminEventActivity.java
  divertech/app/src/main/java/Si3/divertech/events/EventActivities.java
  divertech/app/src/main/java/Si3/divertech/events/EventList.java
  divertech/app/src/main/java/Si3/divertech/notifications/NotificationList.java
  divertech/app/src/main/java/Si3/divertech/qr_reader/CameraPreviewActivity.java
  divertech/app/src/main/java/Si3/divertech/users/ProfileActivity.java
  divertech/app/src/main/java/Si3/divertech/users/ProfileController.java
  divertech/app/src/main/java/Si3/divertech/users/ProfileView.java
  divertech/app/src/main/java/Si3/divertech/users/User.java
  divertech/app/src/main/java/Si3/divertech/users/UserData.java
  divertech/app/src/main/res/layout/activity_admin_event.xml
  divertech/app/src/main/res/layout/activity_lauch.xml
  divertech/app/src/main/res/values/strings.xml
Labels: enhancement
